print("\n")
print("               /pIVp&^p%$@+\    [\        (Ds          E!3         /#<                                          ")
print("              /*/          ^#    py      /Y/          @(*         $*s                                          ")
print("             <^/           N$     IV    /&E          &^#         <*9                                        ")
print("            :sA          ^$        yu  /@f   Ie&^(#msd)sI%;4O%  $u^                                           ")
print("           #!3/##@##%&#E*           yyU&          +R=          /<C                                             ")
print("          /Pp                       /&%          #$s          &^$ /:[]U%=._     _+ON&$*$@=_      @$*_=OF*$=_          ")
print("         /]+                       0s^          *DS          #9s?*       <h    #?+      {*D     UR#*       RW        ")
print("        IOE                       #&*          @ni          !~U         #&$   #84       $*D    ($J        C^R     ")
print("       /%*                       <[/          ?.C          ILV         f)%    *v!      P*$    NDI        *@B        ")
print("      ^&#                       $#w          %4)          I_U         C^I      *&$CS*$N^*    <D*        ~&#       ")
print("\n") 